/// Row from `bookings`. Can also carry joined data:
/// `select('*, profiles(full_name), bays(label, level)')`.
class Booking {
  const Booking({
    required this.id,
    required this.driverId,
    required this.facilityId,
    required this.startTime,
    required this.endTime,
    required this.status,
    required this.bookingCode,
    this.bayId,
    this.vehicleNumber,
    this.createdAt,
    this.driverName,
    this.bayLabel,
    this.bayLevel,
  });

  static const String reserved = 'reserved';
  static const String active = 'active';
  static const String completed = 'completed';
  static const String cancelled = 'cancelled';
  static const String expired = 'expired';

  final String id;
  final String driverId;
  final String facilityId;
  final String? bayId;
  final String? vehicleNumber;
  final DateTime startTime; // local time
  final DateTime endTime; // local time
  final String status;
  final String bookingCode; // e.g. PP-1A2B3C (also the QR payload)
  final DateTime? createdAt;

  // joined
  final String? driverName;
  final String? bayLabel;
  final String? bayLevel;

  bool get isLive => status == reserved || status == active;
  bool get hasBay => bayId != null;

  String get bayDisplay {
    if (bayLabel == null) return 'Not assigned';
    return bayLevel == null ? bayLabel! : '$bayLabel · $bayLevel';
  }

  factory Booking.fromMap(Map<String, dynamic> m) {
    final driver = m['profiles'];
    final bay = m['bays'];
    return Booking(
      id: m['id'] as String,
      driverId: m['driver_id'] as String,
      facilityId: m['facility_id'] as String,
      bayId: m['bay_id'] as String?,
      vehicleNumber: m['vehicle_number'] as String?,
      startTime: DateTime.parse(m['start_time'] as String).toLocal(),
      endTime: DateTime.parse(m['end_time'] as String).toLocal(),
      status: (m['status'] as String?) ?? reserved,
      bookingCode: (m['booking_code'] as String?) ?? '',
      createdAt: m['created_at'] == null ? null : DateTime.parse(m['created_at'] as String).toLocal(),
      driverName: driver is Map ? driver['full_name'] as String? : null,
      bayLabel: bay is Map ? bay['label'] as String? : null,
      bayLevel: bay is Map ? bay['level'] as String? : null,
    );
  }

  /// Columns for insert (booking_code and id are generated by the database).
  Map<String, dynamic> toMap() => {
        'driver_id': driverId,
        'facility_id': facilityId,
        'bay_id': bayId,
        'vehicle_number': vehicleNumber,
        'start_time': startTime.toUtc().toIso8601String(),
        'end_time': endTime.toUtc().toIso8601String(),
        'status': status,
      };
}
